In [1]:
import numpy as np 
import pandas as pd

In [3]:
[float(x) for x in ['2460056.314567973', '0.17483086495589117', '1.6931706443721604',
 '-2.6242931012724187', '-0.050992853505147574', '-2.3406230073283103',
 '3.8327538685185125']]
            

[2460056.314567973,
 0.17483086495589117,
 1.6931706443721604,
 -2.6242931012724187,
 -0.050992853505147574,
 -2.3406230073283103,
 3.8327538685185125]

In [1]:
import glob
file_lst = glob.glob('/carc/scratch/projects/dragomir/dragomir2016394/mdwarfs/*/fits/*.fits')


In [2]:
len(file_lst)

1930813

In [ ]:
l1 = 2268816
l2 = 2260672

In [2]:


lst = [[(1535.2992324639604, 0.04156841445304313)], [(2266.505366963533, 0.012831447467606344)], [(2332.4362359258216, 0.002623771250610378), (1593.7157159196274, 0.002385701771787125), (2063.1057954407356, 0.002511441370983683), (2326.849823692921, 0.002740556773962934)], [(1526.8120046300492, 0.0014404288397240612), (1539.7722720329607, 0.0014235886198028093), (1355.293198964669, 0.0017595295947192553), (1361.5794450841126, 0.0012901187729719235), (1523.8144246023066, 0.0014679934849563827), (1623.7803780346787, 0.0016536108370125233)]]


len(lst)

4

In [9]:
len('yes')

3

In [2]:
[x-y for x in [1526.812, 1539.7723, 1523.8144] for y in [1526.812, 1539.7723, 1523.8144]]

[0.0,
 -12.960300000000188,
 2.9975999999999203,
 12.960300000000188,
 0.0,
 15.957900000000109,
 -2.9975999999999203,
 -15.957900000000109,
 0.0]

In [4]:
12.960300000000188-15.957900000000109


-2.9975999999999203

In [18]:
8.9033 /3.691

2.4121647250067735

In [ ]:
P=1.2628 d, SNR=12.42 (min 10.0)
Candidate: P=2.4603 d, SNR=6.62 (min 10.0)
Candidate: P=8.9033 

In [15]:
import numpy as np
arr = np.array([10, 2, 5])
divisors = np.arange(1, 3 + 1, dtype=float)

diffs = abs(arr[:, None]  - arr[None, :] ) 

trial_periods = (diffs[:, None] / divisors[None, :]).ravel()

trial_periods[trial_periods > 1]

array([4.        , 1.66666667, 8.        , 5.        , 1.5       ])

In [3]:
for x in lst:
    print(x)

[(1535.2992324639604, 0.04156841445304313)]
[(2266.505366963533, 0.012831447467606344)]
[(2332.4362359258216, 0.002623771250610378), (1593.7157159196274, 0.002385701771787125), (2063.1057954407356, 0.002511441370983683), (2326.849823692921, 0.002740556773962934)]
[(1526.8120046300492, 0.0014404288397240612), (1539.7722720329607, 0.0014235886198028093), (1355.293198964669, 0.0017595295947192553), (1361.5794450841126, 0.0012901187729719235), (1523.8144246023066, 0.0014679934849563827), (1623.7803780346787, 0.0016536108370125233)]


In [7]:



[(1526.8120046300492, 0.0014404288397240612), (1539.7722720329607, 0.0014235886198028093), (1355.293198964669, 0.0017595295947192553), (1361.5794450841126, 0.0012901187729719235), (1523.8144246023066, 0.0014679934849563827), (1623.7803780346787, 0.0016536108370125233)]

t0_vals2 = [x[0] for x in lst[3]]



In [72]:
t0_vals




[2332.4362359258216, 1593.7157159196274, 2063.1057954407356, 2326.849823692921]

In [71]:
all_t0

array([[1526.81200463, 1539.77227203, 1355.29319896, 1361.57944508,
        1523.8144246 , 1623.78037803],
       [1526.81200463, 1539.77227203, 1355.29319896, 1361.57944508,
        1523.8144246 , 1623.78037803],
       [1526.81200463, 1539.77227203, 1355.29319896, 1361.57944508,
        1523.8144246 , 1623.78037803],
       [1526.81200463, 1539.77227203, 1355.29319896, 1361.57944508,
        1523.8144246 , 1623.78037803],
       [1526.81200463, 1539.77227203, 1355.29319896, 1361.57944508,
        1523.8144246 , 1623.78037803],
       [1526.81200463, 1539.77227203, 1355.29319896, 1361.57944508,
        1523.8144246 , 1623.78037803]])

In [9]:
1526.8120046300492 - 1539.7722720329607

-12.96026740291154

In [12]:
1523.8144246023066-1526.8120046300492

-2.997580027742515

In [75]:
val

array([  2.99758003,   6.28624612,  12.9602674 ,  15.95784743,
        84.008106  ,  96.9683734 ,  99.96595343, 162.23497952,
       165.23255955, 168.52122564, 171.51880567, 178.19282695,
       184.47907307, 262.20093295, 268.48717907])

In [266]:
def keep_unique_period_indices(periods, merge_tol=0.02):
    kept = []

    for i, Pi in enumerate(periods):
        keep = True

        for j in kept:
            Pj = periods[j]

            if abs(Pi - Pj) / Pj < merge_tol:
                keep = False
                break

        if keep:
            kept.append(i)

    return kept

def potential_periods_from_single_dt_events(t0s, min_support=3, perc_tol = 0.02, max_ratio = 3, P_min = 1):
#     t0s = [ev.t0_days for ev in events]
    
    potential_periods = np.unique(np.abs([x-y for x in t0s for y in t0s]))[1:]
    
    ratios = np.array([potential_periods/x for x in potential_periods])
#     print(ratios)
    all_checks  = np.array([ratios*x for x  in range(1, max_ratio+1)])
    all_checks[all_checks<=1] = np.nan
    
    all_periods = []
    matches = np.zeros(ratios.shape, dtype = bool)
    for iii, ary_check in enumerate(all_checks):
        percent_diff = np.abs((ary_check - np.round(ary_check))/ary_check)
        close = percent_diff<perc_tol
        check_close = np.nansum(close, axis = 1)>=min_support
            
        all_periods.extend(list(potential_periods[check_close]/(iii+1)))
#     all_periods = np.array([x for x in ary for ary in all_periods])
#     print(all_periods)
    all_periods_indxs = keep_unique_period_indices(all_periods)
    final_periods     = np.unique(np.array(all_periods)[all_periods_indxs])
    return final_periods[final_periods>P_min]

In [267]:
pers = potential_periods_from_single_dt_events(t0_vals)

In [274]:
pers = np.ravel(np.array([[pers*x] for x in [0.5, 1., 2]]))
pers[keep_unique_period_indices(pers)]

array([ 0.93106871,  1.39660306,  2.79320612,  1.86213741,  5.58641223,
        3.72427482, 11.17282447])

In [224]:
val = np.unique(np.abs([x-y for x in t0_vals2 for y in t0_vals2]))[1:]
ary = np.array([val/x for x in val])


np.array([ary*x for x  in range(1, 3+1)])[1]

array([[2.00000000e+00, 4.19421404e+00, 8.64715356e+00, 1.06471536e+01,
        5.60506176e+01, 6.46977712e+01, 6.66977712e+01, 1.08243969e+02,
        1.10243969e+02, 1.12438183e+02, 1.14438183e+02, 1.18891122e+02,
        1.23085336e+02, 1.74941740e+02, 1.79135954e+02],
       [9.53694771e-01, 2.00000000e+00, 4.12337257e+00, 5.07706734e+00,
        2.67275905e+01, 3.08509631e+01, 3.18046578e+01, 5.16158535e+01,
        5.25695483e+01, 5.36158535e+01, 5.45695483e+01, 5.66929209e+01,
        5.86929209e+01, 8.34205114e+01, 8.54205114e+01],
       [4.62579966e-01, 9.70079694e-01, 2.00000000e+00, 2.46257997e+00,
        1.29639464e+01, 1.49639464e+01, 1.54265264e+01, 2.50357457e+01,
        2.54983257e+01, 2.60058254e+01, 2.64684054e+01, 2.74983257e+01,
        2.84684054e+01, 4.04622721e+01, 4.14323518e+01],
       [3.75687265e-01, 7.87856401e-01, 1.62431274e+00, 2.00000000e+00,
        1.05287516e+01, 1.21530644e+01, 1.25287516e+01, 2.03329403e+01,
        2.07086276e+01, 2.11207967e+0

In [212]:
potential_periods_from_single_dt_events(t0_vals)

IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

In [222]:
val = np.unique(np.abs([x-y for x in t0_vals2 for y in t0_vals2]))[1:]
ary = np.array([val/x for x in val])

# ary[ary<=1] = np.nan

per_ratios_t0_check = sorted(per_ratios_t0_check[per_ratios_t0_check>1])
per_ratios_t0_check
# percent_diff = np.abs((ary - per_ratios_t0_check)/ary)
# percent_diff



TypeError: '>' not supported between instances of 'list' and 'int'

In [174]:
val

array([  2.99758003,   6.28624612,  12.9602674 ,  15.95784743,
        84.008106  ,  96.9683734 ,  99.96595343, 162.23497952,
       165.23255955, 168.52122564, 171.51880567, 178.19282695,
       184.47907307, 262.20093295, 268.48717907])

In [173]:
val[np.nansum(np.nansum(perc_diff<0.05, axis = 2)>0, axis = 1)>3]

array([  2.99758003,   6.28624612,  12.9602674 ,  15.95784743,
        84.008106  ,  96.9683734 ,  99.96595343, 162.23497952,
       165.23255955])

In [202]:
percent_diff =np.abs(ary - np.round(ary))/ary

bool_sim = (percent_diff<0.02)
np.sum(bool_sim, axis = 1)

array([11,  9,  7,  4,  2,  0,  0,  1,  1,  1,  0,  0,  0,  0,  0])

In [199]:
pers

array([ 2.99758003,  6.28624612, 12.9602674 , 15.95784743])

array([ 2.99758003,  3.28866609,  6.67402128,  9.67160131,  9.96268738,
       12.9602674 ])

In [198]:
check_pers

array([[0.00000000e+00, 4.63052287e-02, 7.48400679e-02, 6.07818377e-02,
        9.03070293e-04, 1.07850888e-02, 1.04616870e-02, 2.25387904e-03,
        2.21299011e-03, 3.89710009e-03, 3.82899170e-03, 7.49528101e-03,
        7.43113367e-03, 5.38316367e-03, 4.82340882e-03],
       [9.71070201e-02, 4.63052287e-02, 1.49994562e-02, 3.04228393e-02,
        1.78222371e-02, 1.64698725e-02, 1.30641547e-02, 6.72075176e-03,
        4.83715173e-03, 4.74275545e-03, 2.96275907e-03, 3.39440149e-03,
        1.70085380e-03, 3.40332269e-03, 4.40780991e-03],
       [1.00000000e+00, 6.16862841e-02, 2.99203058e-02, 1.63543666e-01,
        3.27845825e-02, 3.24017588e-02, 1.44414988e-03, 1.26881929e-02,
        9.79209270e-03, 9.91384643e-03, 1.16940396e-02, 1.12560519e-02,
        1.29744953e-02, 7.30013762e-03, 5.68491850e-03],
       [1.00000000e+00, 5.38533670e-01, 2.53749864e-01, 2.12143599e-01,
        3.61430098e-02, 2.60250104e-03, 3.25104719e-02, 1.34511237e-02,
        4.93448300e-03, 2.43530352e-0